version: '3'

services:
  database:
    image: postgres:10
    ports:
      - ${DATABASE_PORT:-5432}:5432
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-pass}
      - POSTGRES_USER=${DATABASE_USER:-username}
      - POSTGRES_DB=${DATABASE_NAME:-database}
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
      - /tmp:/tmp

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./hctest:/code
    ports:
      - ${APP_PORT:-80}:8000
    environment:
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-pass}
      - DATABASE_USER=${DATABASE_USER:-user}
      - DATABASE_NAME=${DATABASE_NAME:-db}
      - DATABASE_HOST=${DATABASE_HOST:-db}
      - DATABASE_PORT=${DATABASE_PORT:-5432}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost}:-localhost
    links:
      - database
